name: Rust

on:
  push:
    branches: [ "main", "test-build" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: sh build-wasm.sh
