name: Rust

on:
  push:
    branches: "main"
    paths:
      - '/src/**'
      - '/assets/**'
      - '.github/workflows/rust.yml'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Install  libasound2-dev
      run: sudo apt-get install -y libasound2-dev
    - uses: Swatinem/rust-cache@v2
      with: 
         cache-all-crates: true
    - name: Install wasm-bindgen
      run: cargo install wasm-bindgen-cli
    - name: Build
      run: cargo build --release --target wasm32-unknown-unknown
    - name: Make wasm-build directory
      run: mkdir wasm-build
    - name: Make wasm-build assets directory
      run: mkdir wasm-build/assets
    - name: Bindgen
      run: wasm-bindgen --no-typescript --target web --out-dir ./wasm-build/ --out-name "bevy-flappy-pebble" ./target/wasm32-unknown-unknown/release/bevy-flappy-pebble.wasm
    - name: Copy sprites
      run: cp ./assets/*.png ./wasm-build/assets
    - name: Copy index.html
      run: cp ./assets/index.html ./wasm-build
    - name: Upload a Build Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: wasm-build

  publish-pages:
    needs: build-wasm
    runs-on: ubuntu-latest
    steps:
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v2
