name: Rust

on:
  push:
    branches: [ "main", "test-build" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install wasm target
      run: rustup target add wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
    - name: Install wasm-bindgen
      run: cargo install wasm-bindgen-cli
    - name: Build
      run: cargo build --release --target wasm32-unknown-unknown
    - name: Make wasm-build directory
      run: mkdir wasm-build
    - name: Make wasm-build assets directory
      run: mkdir wasm-build/assets
    - name: Bindgen
      run: wasm-bindgen --no-typescript --target web --out-dir ./wasm-build/ --out-name "bevy-flappy-pebble" ./target/wasm32-unknown-unknown/release/bevy-flappy-pebble.wasm
    - name: Copy sprites
      run: cp ./assets/*.png ./wasm-build/assets
    - name: Copy index.html
      run: cp ./assets/index.html ./wasm-build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: wasm-build
        path: wasm-build
        if-no-files-found: error

  publish-pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.2
      with:
        artifact_name: wasm-build
